spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_size: 100
  messages:
    basename: errors

#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html

server:
  serlvet:
    session:
      tracking-modes: cookie
      timeout: 1800


logging:
  level:
    org.hibernate.SQL: debug